[general]
servername=asterisk
enabled=yes
bindaddr=0.0.0.0
bindport=8088
prefix=asterisk
enablestatic=yes
redirect = / /static/index.html
tlsenable=yes
tlsbindaddr=0.0.0.0:8089
tlscertfile=/var/lib/asterisk/ssl/asterisk.pem
tlsprivatekey=/var/lib/asterisk/ssl/asterisk.key
