// SIP transaction state machines (RFC 3261 §17).
//
// Four flavours are supported:
//   * InviteServerTransaction      (§17.2.1) — Proceeding/Completed/Confirmed/Accepted/Terminated
//   * NonInviteServerTransaction   (§17.2.2) — Trying/Proceeding/Completed/Terminated
//   * InviteClientTransaction      (§17.1.1) — Calling/Proceeding/Completed/Accepted/Terminated
//   * NonInviteClientTransaction   (§17.1.2) — Trying/Proceeding/Completed/Terminated
//
// The implementation is intentionally compact: response/ACK retransmits are
// absorbed using the timer values from `lib/sip_2/timers.dart`. The transport
// layer is abstracted via a `send` callback rather than coupling to the
// existing `SipTransport` so unit tests can drive it without a real socket.

import 'dart:async';

import 'package:dart_pbx/sip_2/timers.dart';
import 'package:dart_pbx/sip_parser/sip.dart';

import 'sip_helpers.dart';

enum TxKind { inviteServer, nonInviteServer, inviteClient, nonInviteClient }

enum TxState {
  trying,
  calling,
  proceeding,
  completed,
  confirmed,
  accepted,
  terminated,
}

typedef TxSendFn = void Function(String rawMessage);

/// Common base for all four transaction types. Concrete subclasses are below.
abstract class Transaction {
  Transaction({
    required this.kind,
    required this.id,
    required this.branch,
    required this.method,
    required this.send,
    required this.reliable,
  }) : state = _initialState(kind);

  final TxKind kind;

  /// Unique key used by the transaction layer (see [TransactionLayer.keyFor]).
  final String id;

  /// Top-most Via branch (with magic cookie) captured at creation time.
  final String branch;

  /// Method this transaction was created for. ACK/CANCEL are matched against
  /// the original INVITE transaction; this field always holds the *original*
  /// method (e.g. "INVITE", never "ACK").
  final String method;

  /// Transport callback for sending bytes downstream / upstream.
  final TxSendFn send;

  /// True when running over a reliable transport (TCP/TLS/WS): suppresses the
  /// request retransmit Timer A and shortens absorb timers per §17.
  final bool reliable;

  TxState state;

  /// Last final/provisional response (for absorb-and-resend).
  String? lastResponse;

  /// Optional callback fired when the transaction reaches `terminated`.
  void Function()? onTerminate;

  final List<Timer> _timers = [];

  bool get isTerminated => state == TxState.terminated;

  void _arm(Timer t) => _timers.add(t);

  /// Cancel every armed timer and mark the transaction terminated.
  void terminate() {
    if (state == TxState.terminated) return;
    state = TxState.terminated;
    for (final t in _timers) {
      t.cancel();
    }
    _timers.clear();
    onTerminate?.call();
  }

  static TxState _initialState(TxKind k) {
    switch (k) {
      case TxKind.inviteServer:
        return TxState.proceeding;
      case TxKind.nonInviteServer:
        return TxState.trying;
      case TxKind.inviteClient:
        return TxState.calling;
      case TxKind.nonInviteClient:
        return TxState.trying;
    }
  }
}

// ---------------------------------------------------------------------------
// Server side
// ---------------------------------------------------------------------------

/// Server transaction for INVITE (RFC 3261 §17.2.1). Handles 1xx/2xx/3xx-6xx
/// response transmission and ACK absorption, plus retransmit of final non-2xx
/// responses every Timer G doubling up to T2 until ACK or Timer H.
class InviteServerTransaction extends Transaction {
  InviteServerTransaction({
    required String id,
    required String branch,
    required TxSendFn send,
    required bool reliable,
  }) : super(
          kind: TxKind.inviteServer,
          id: id,
          branch: branch,
          method: 'INVITE',
          send: send,
          reliable: reliable,
        );

  int _gInterval = Timers.T1;
  Timer? _timerG;
  Timer? _timerH;
  Timer? _timerI;
  Timer? _timerL;

  /// Send an automatic 100 Trying generated by the proxy itself.
  void sendTrying(SipMsg request) {
    if (state != TxState.proceeding) return;
    final raw = buildResponse(request, code: 100, reason: 'Trying');
    lastResponse = raw;
    send(raw);
  }

  /// Send the constructed [response] (final or provisional) back to the UAC.
  void sendResponse(String response, int code) {
    lastResponse = response;
    send(response);
    if (code < 200) {
      // Stay in Proceeding.
      return;
    }
    if (code < 300) {
      if (state == TxState.accepted) return; // already absorbing 2xx retx
      // 2xx: per RFC 6026 we move to Accepted and absorb retransmits via Timer L.
      state = TxState.accepted;
      _timerL = Timer(const Duration(milliseconds: Timers.TIMER_L), terminate);
      _arm(_timerL!);
      return;
    }
    // 3xx-6xx: Completed, retransmit response on Timer G until ACK or Timer H.
    if (state == TxState.completed ||
        state == TxState.confirmed ||
        state == TxState.terminated) {
      // Already in completed: a duplicate final response from upstream
      // shouldn't reset our Timer G/H or move us out of confirmed/terminated.
      return;
    }
    state = TxState.completed;
    if (!reliable) {
      _scheduleG();
    }
    _timerH = Timer(const Duration(milliseconds: Timers.TIMER_H), () {
      // ACK never arrived; transport timeout.
      terminate();
    });
    _arm(_timerH!);
  }

  void _scheduleG() {
    _timerG = Timer(Duration(milliseconds: _gInterval), () {
      if (state != TxState.completed) return;
      if (lastResponse != null) send(lastResponse!);
      _gInterval = (_gInterval * 2).clamp(Timers.T1, Timers.T2);
      _scheduleG();
    });
    _arm(_timerG!);
  }

  /// Called when an INVITE retransmit arrives. Re-sends the last response if
  /// we are in Proceeding/Completed.
  void onRequestRetransmit() {
    if (state == TxState.proceeding || state == TxState.completed) {
      if (lastResponse != null) send(lastResponse!);
    }
  }

  /// Called when an ACK arrives (only meaningful for Completed-state).
  /// Returns true if the ACK was absorbed by this transaction (i.e. ACK to
  /// non-2xx). The proxy uses the return value to decide whether to forward.
  bool onAck() {
    if (state == TxState.completed) {
      _timerG?.cancel();
      _timerH?.cancel();
      state = TxState.confirmed;
      if (reliable) {
        terminate();
      } else {
        _timerI = Timer(const Duration(milliseconds: 5000), terminate);
        _arm(_timerI!);
      }
      return true; // absorbed — do not forward
    }
    // ACK to a 2xx is a brand-new transaction; let the proxy forward it.
    return false;
  }
}

/// Server transaction for non-INVITE methods (RFC 3261 §17.2.2).
class NonInviteServerTransaction extends Transaction {
  NonInviteServerTransaction({
    required String id,
    required String branch,
    required String method,
    required TxSendFn send,
    required bool reliable,
  }) : super(
          kind: TxKind.nonInviteServer,
          id: id,
          branch: branch,
          method: method,
          send: send,
          reliable: reliable,
        );

  Timer? _timerJ;

  void sendResponse(String response, int code) {
    lastResponse = response;
    send(response);
    if (code < 200) {
      state = TxState.proceeding;
      return;
    }
    state = TxState.completed;
    if (reliable) {
      terminate();
    } else {
      _timerJ = Timer(const Duration(milliseconds: Timers.TIMER_J), terminate);
      _arm(_timerJ!);
    }
  }

  void onRequestRetransmit() {
    if (state == TxState.proceeding || state == TxState.completed) {
      if (lastResponse != null) send(lastResponse!);
    }
  }
}

// ---------------------------------------------------------------------------
// Client side
// ---------------------------------------------------------------------------

/// Client transaction for INVITE (RFC 3261 §17.1.1). Retransmits the request
/// on Timer A doubling, gives up at Timer B, absorbs late responses on Timer D.
class InviteClientTransaction extends Transaction {
  InviteClientTransaction({
    required String id,
    required String branch,
    required TxSendFn send,
    required bool reliable,
    required this.request,
  }) : super(
          kind: TxKind.inviteClient,
          id: id,
          branch: branch,
          method: 'INVITE',
          send: send,
          reliable: reliable,
        );

  /// Raw INVITE that started this transaction. We keep it so we can build a
  /// matching ACK for non-2xx responses (RFC 3261 §17.1.1.3).
  final String request;

  int _aInterval = Timers.T1;
  Timer? _timerA;
  Timer? _timerB;
  Timer? _timerD;

  /// Callback fired on a final response (>=200). Receives the raw response
  /// string. The proxy uses this to forward the response upstream.
  void Function(String rawResponse, int code)? onFinalResponse;

  /// Callback for provisional responses (1xx, code != 100).
  void Function(String rawResponse, int code)? onProvisional;

  void start() {
    send(request);
    if (!reliable) _scheduleA();
    _timerB = Timer(const Duration(milliseconds: Timers.TIMER_B), () {
      // Transaction timeout; treat as 408.
      terminate();
    });
    _arm(_timerB!);
  }

  void _scheduleA() {
    _timerA = Timer(Duration(milliseconds: _aInterval), () {
      if (state != TxState.calling) return;
      send(request);
      _aInterval *= 2;
      _scheduleA();
    });
    _arm(_timerA!);
  }

  void onResponse(String raw, int code) {
    lastResponse = raw;
    if (code < 200) {
      _timerA?.cancel();
      state = TxState.proceeding;
      onProvisional?.call(raw, code);
      return;
    }

    // 2xx final.
    if (code < 300) {
      _timerA?.cancel();
      _timerB?.cancel();
      if (state == TxState.accepted || state == TxState.terminated) {
        // Duplicate 2xx — let the upper layer absorb retransmits, do not
        // refire onFinalResponse (would forward downstream twice).
        return;
      }
      state = TxState.accepted;
      onFinalResponse?.call(raw, code);
      _timerD = Timer(const Duration(milliseconds: Timers.TIMER_M), terminate);
      _arm(_timerD!);
      return;
    }

    // 3xx-6xx final. RFC 3261 §17.1.1.3: the ICT MUST generate an ACK and
    // send it to the same downstream hop as the INVITE. The ACK absorbs
    // upstream retransmits so the UAS stops re-sending the final.
    final ack = _buildAckForNon2xx(raw);
    send(ack);

    if (state == TxState.completed || state == TxState.terminated) {
      // A retransmitted non-2xx final. Re-send the ACK only (already done
      // above) and DO NOT refire onFinalResponse — that would push another
      // copy downstream, restart the IST's Timer G, and fork the storm.
      return;
    }

    _timerA?.cancel();
    _timerB?.cancel();
    state = TxState.completed;
    onFinalResponse?.call(raw, code);
    if (reliable) {
      terminate();
    } else {
      _timerD = Timer(const Duration(milliseconds: 32000), terminate);
      _arm(_timerD!);
    }
  }

  /// Builds an RFC 3261 §17.1.1.3 ACK for a non-2xx final response.
  /// Reuses the Via (with the original branch), Call-ID, From, To (with the
  /// response's To-tag), and CSeq number from the original INVITE.
  String _buildAckForNon2xx(String response) {
    String? toHeader;
    for (final line in response.split('\r\n')) {
      if (line.isEmpty) break;
      if (line.toLowerCase().startsWith('to:') ||
          line.toLowerCase().startsWith('t:')) {
        toHeader = line;
        break;
      }
    }

    final reqHeaderEnd = request.indexOf('\r\n\r\n');
    final reqHeaders =
        (reqHeaderEnd < 0 ? request : request.substring(0, reqHeaderEnd))
            .split('\r\n');
    if (reqHeaders.isEmpty) return request;

    // Request line: INVITE → ACK, keep Request-URI.
    reqHeaders[0] = reqHeaders[0].replaceFirst(RegExp(r'^INVITE\b'), 'ACK');

    final out = <String>[reqHeaders[0]];
    var seenContentLen = false;
    var seenTo = false;
    for (var i = 1; i < reqHeaders.length; i++) {
      final h = reqHeaders[i];
      final lower = h.toLowerCase();
      if (lower.startsWith('cseq:')) {
        // Same number, method = ACK.
        final num =
            h.substring(h.indexOf(':') + 1).trim().split(RegExp(r'\s+')).first;
        out.add('CSeq: $num ACK');
        continue;
      }
      if (lower.startsWith('content-length:')) {
        out.add('Content-Length: 0');
        seenContentLen = true;
        continue;
      }
      if ((lower.startsWith('to:') || lower.startsWith('t:')) &&
          toHeader != null) {
        out.add(toHeader); // pick up the To-tag from the response
        seenTo = true;
        continue;
      }
      // Drop any body-influencing headers, keep everything else (Via, From,
      // Call-ID, Max-Forwards, Route, etc.).
      if (lower.startsWith('content-type:')) continue;
      out.add(h);
    }
    if (!seenContentLen) out.add('Content-Length: 0');
    if (!seenTo && toHeader != null) out.add(toHeader);
    return '${out.join('\r\n')}\r\n\r\n';
  }
}

/// Client transaction for non-INVITE methods (RFC 3261 §17.1.2).
class NonInviteClientTransaction extends Transaction {
  NonInviteClientTransaction({
    required String id,
    required String branch,
    required String method,
    required TxSendFn send,
    required bool reliable,
    required this.request,
  }) : super(
          kind: TxKind.nonInviteClient,
          id: id,
          branch: branch,
          method: method,
          send: send,
          reliable: reliable,
        );

  final String request;

  int _eInterval = Timers.T1;
  Timer? _timerE;
  Timer? _timerF;
  Timer? _timerK;

  void Function(String rawResponse, int code)? onFinalResponse;
  void Function(String rawResponse, int code)? onProvisional;

  void start() {
    send(request);
    if (!reliable) _scheduleE();
    _timerF = Timer(const Duration(milliseconds: Timers.TIMER_F), terminate);
    _arm(_timerF!);
  }

  void _scheduleE() {
    _timerE = Timer(Duration(milliseconds: _eInterval), () {
      if (state == TxState.terminated) return;
      send(request);
      _eInterval = (_eInterval * 2).clamp(Timers.T1, Timers.T2);
      _scheduleE();
    });
    _arm(_timerE!);
  }

  void onResponse(String raw, int code) {
    lastResponse = raw;
    if (code < 200) {
      state = TxState.proceeding;
      onProvisional?.call(raw, code);
      return;
    }
    _timerE?.cancel();
    _timerF?.cancel();
    state = TxState.completed;
    onFinalResponse?.call(raw, code);
    if (reliable) {
      terminate();
    } else {
      _timerK = Timer(const Duration(milliseconds: Timers.T4), terminate);
      _arm(_timerK!);
    }
  }
}
